version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    command: sh -c "poetry run python manage.py migrate --no-input && poetry run python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
