# Generated by Django 4.0.4 on 2022-05-19 22:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checking_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='BillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.TextField()),
                ('reason', models.CharField(blank=True, choices=[('DEPOSITED', 'Deposited'), ('BILLED', 'Billed'), ('REFUNDED', 'Refunded'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('from_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='balance.bill')),
                ('to_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='balance.bill')),
            ],
            options={
                'verbose_name': 'Транзакцию между счетами',
                'verbose_name_plural': 'Транзакции между счетами',
            },
        ),
        migrations.CreateModel(
            name='BillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_after_transaction', models.DecimalField(decimal_places=6, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balance.bill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balance.billtransaction')),
            ],
            options={
                'verbose_name': 'Checking account entry',
                'verbose_name_plural': 'Checking account entries',
            },
        ),
        migrations.CreateModel(
            name='AccountBillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('comment', models.TextField()),
                ('reason', models.CharField(blank=True, choices=[('DEPOSITED', 'Deposited'), ('BILLED', 'Billed'), ('REFUNDED', 'Refunded'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('from_bills', models.ManyToManyField(related_name='from_bills', to='balance.bill')),
                ('to_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_bill', to='balance.bill')),
            ],
            options={
                'verbose_name': 'Транзакцию между счетами',
                'verbose_name_plural': 'Транзакции между счетами',
            },
        ),
    ]
