# Generated by Django 4.0.4 on 2022-05-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbilltransaction',
            options={'verbose_name': 'Транзакцию между пользователем', 'verbose_name_plural': 'Транзакции между пользователями'},
        ),
    ]
