# Generated by Django 4.0.4 on 2022-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_accountbilltransaction_from_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbilltransaction',
            name='reason',
            field=models.CharField(choices=[('CANCELED', 'Deposited'), ('BILLED', 'Billed'), ('REFUNDED', 'Refunded'), ('OTHER', 'Other')], default='CANCELED', max_length=255),
        ),
        migrations.AlterField(
            model_name='billtransaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('CANCELED', 'Deposited'), ('BILLED', 'Billed'), ('REFUNDED', 'Refunded'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
